### ISSUE TITLE
Cannot find module 'livetex-node-pg'

### ISSUE THREAD

**Issue by kruatech** [LiveTex/Node-Pg#6]
Поставил расширение.
Решил запустить пример из мануала. "var pg = require('livetex-node-pg');"

Выдает ошибку.
Error: Cannot find module 'livetex-node-pg'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object. (/home/developer/temp/pg.js:1:72)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)

Хотя в папке node_modules есть папка livetex-node-pg

**Comment by valeriakononenko** [comment]
починено в livetex-node-pg@2.0.1
